config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :users 
resources :candidates
# resources :job_posts
root "candidates#dashboard"
  # get 'sessions/new'
  get    'sign_in', to: 'sessions#new'
  post   'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'dashboard', to: 'candidates#dashboard'
  get 'approve/:id', to: 'users#approval', as: :approved
  get 'decline/:id', to: 'users#decline', as: :declined
  get 'probing', to: 'candidates#probing', as: :probing
  post 'probing', to: 'candidates#modify' 
  get 'docs_submission', to: 'candidate_clears#new'
  post 'docs_submission', to: 'candidate_clears#create'
  get 'docs_view', to: 'candidate_clears#index'
  get 'job_posts', to: 'job_posts#index'
  get 'job_posts/new', to: 'job_posts#new'
  post 'job_posts/new', to: 'job_posts#create'
  get '/job_post/:id', to: 'job_posts#show'
  get '/job_posts/:id/edit', to: 'job_posts#edit', as: :edit_jobpost
  put '/job_posts/:id', to: 'job_posts#update', as: :update_post
  delete '/job_posts/:id', to: 'job_posts#destroy'
  get 'post_approve/:id', to: 'job_posts#approval', as: :post_approved
  get 'post_decline/:id', to: 'job_posts#declined', as: :post_declined
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	belongs_to :role
 #  validates :first_name, presence: true
 #  validates :last_name, presence: true
 #  validates :email, presence: true, email:true, confirmation: true, uniqueness: true
 #  validates :email_confirmation, presence: { message: "must be given correctly" }, on: :create
 #  validates :role_id, presence: true, length: { maximum:1 }
 #  validates :password, format: {with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\z/, message: 'need alphabet, numbers and special characters'}, confirmation: true
 #  validates :password_confirmation, presence: { message: "must be same as password" }, on: :create
  enum status: {
    stat_pending: 0, 
    stat_approved: 1, 
    stat_declined:2 
  }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_login, except: [:new, :create]
  # before_action :restrict, only: [:edit, :destroy ]
  # before_action :logged_in, except: [:index, :show, :edit, :update, :destroy, :approval, :decline]
  before_action :authenticate_user!

	def index
   # @users = User.search(
   search = params[:q]
   # if require_login
   #  redirect_to root_path
   # end
    @users = if search
      User.joins(:role).where('first_name LIKE :search OR roles.designation LIKE :search', search: "%#{search}%")
    else
      User.all
   end
	end

	def show 
		@user = User.find(params[:id])
	end

	def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # binding.pry
      redirect_to new_user_path, notice: "Your request have been sent succesfully for approval"
    else
      render :new
    end
  end

  def edit
    # if is_hr || is_sd
    #   flash[:error] = "You must be logged in as admin to access this action"
    #   redirect_to users_path
    # else
      @user = User.find(params[:id])
    # end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|   
      format.html { redirect_to user_url, flash[:error] = "User was Deleted" }   
      format.json { head :no_content }   
      format.js 
    end
  end

  def approval
    @selected_user = User.find(params[:id])
    @selected_user.stat_approved!
    redirect_to users_path
    flash[:notice] = "Request Approved"
  end

  def decline
    @selected_user = User.find(params[:id])
    @selected_user.stat_declined!
    redirect_to users_path
    flash[:notice] = "Request Denied"
  end
  
  private
  def user_params
    params.require(:user).permit(:first_name ,:last_name, :email, :password, :role_id, :password_confirmation, :avatar)
  end

  def restrict
    # binding.pry
    # redirect_to root_path unless current_user.role.designation == "Director"
    # flash[:notice] = "You need to be admin for this action. Please login as one"

    if current_user.role.designation != "Director"
    redirect_to root_path, notice: "You need to be admin for this action. Please login as one"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
   <%= msg %>
  </div>
<% end %>  
<div class="card">
  <div class="card-body">
    <div class="mb-3">
      <%= form.label :first_name, { class: "form-label"}%><br>
      <div>
        <%= form.text_field :first_name , { class: "form-control" }%>
        <% @user.errors.full_messages_for(:first_name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    </div>

    <div class="mb-3">
      <%= form.label :last_name , { class: "form-label"}%><br>
      <%= form.text_field :last_name , { class: "form-control" }%>
      <% @user.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :email, { class: "form-label"} %><br>
      <%= form.text_field :email , { class: "form-control" }%>
      <% @user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :email_confirmation , { class: "form-label"}%><br>
      <%= form.text_field :email_confirmation , { class: "form-control" }%>
      <% @user.errors.full_messages_for(:email_confirmation).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div class="mb-3">
    
    <div>
      <%= form.label :role_id , { class: "form-label"}%><br>
      <%= form.select :role_id, Role.all.pluck(:designation, :id ),{ class:"form-select form-select-lg mb-3" } %>
      <% @user.errors.full_messages_for(:role_id).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div> 

    <div class="mb-3">
      <%= form.label :password, { class: "form-label"} %><br>
      <%= form.password_field :password , { class: "form-control" }%>
      <% @user.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :password_confirmation , { class: "form-label"}%><br>
      <%= form.password_field:password_confirmation , { class: "form-control" }%>
      <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div class="mb-3">
      <%= form.submit %>
    </div>
  </div>
</div>

<% end %>

app/views/users/_index.html.erb
<table class="table table-hover" >
  <tr>
    <th>User ID</th>
    <th>First Name</th>
    <th>Designation</th>
    <%# if is_hr || is_sd %>
    <%# else %>
    <th>Delete</th>
    <th>Login authority</th>
    <%# end%>
  </tr>
 
  <% @users.each do |user| %>
  	<tr id="userRow_<%=user.id%>">
   		<td><a href="/users/<%= user.id %>"><%=user.id%></td>
   		<td><%=user.first_name%></td>
   		<td><%=user&.role&.designation%></td>
    	<%# if is_admin %>
    		<td><%= link_to "Delete", user,
                  method: :delete,
                  data: { confirm: "Are you sure?" }, remote: true %>
      <td><%= user.status%></td>
      <% if user.status == "stat_declined"%>
        <td><%= link_to "Approve", approved_path(id: user.id), remote: true%></td>
      <% elsif user.status == "stat_approved"%>
        <td><%= link_to "Decline", declined_path(id: user.id), remote: true,
                  data: { confirm: "Are you sure?" }%></td>
      <%else%>
        <td><%= link_to "Approve", approved_path(id: user.id), remote: true%>
          &nbsp&nbsp
          <%= link_to "Decline", declined_path(id: user.id), remote: true,
          data: { confirm: "Are you sure?" }%></td>
      <% end%>
  		<%# end%></td>
  	</tr>
  <% end %>
</table>
 
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
   <%= msg %>
  </div>
<% end %>

app/views/users/destroy.js.erb
$("#userRow_<%= @user.id%>").fadeOut();

app/views/users/edit.html.erb
<%= render "candidates/navbar"%>
<h1>Edit User Details</h1>
<%= render "form", user: @user %>
<%= link_to "Back", user_path %>

app/views/users/index.html.erb
<%= render "candidates/navbar"%>
<h1>User details</h1>
<h5>Search</h5>
<%= form_tag(users_path, method: :get, id: "user_search") do%>
<%= text_field_tag(:search, params[:search], id: "search_users")%>
<%#= submit_tag("Search")%>
<%end%>

<div id="users_table">
  <%= render "index"%>
</div>
<%#= link_to "New user", new_user_path , class:"btn btn-outline-primary"%>
<%#= link_to "Existing user", sign_in_path , class:"btn btn-outline-primary"%>
<%= link_to "Search Canidates", candidates_path , class:"btn btn-outline-primary"%>
<%= link_to "Home", root_path , class:"btn btn-outline-primary"%>

<script type="text/javascript">
  $("#search_users").keyup(function(){
    text = $("#search_users").val();
    // console.log("ajax called............" + text);
    $.ajax({
      type: 'GET',
      url: "/users.js",
      data: {"q": text}
    });
  });
</script>

app/views/users/index.js.erb
$("#users_table").html("<%= escape_javascript(render 'index') %>");

app/views/users/new.html.erb
<%= render "candidates/navbar"%>
<h1>Sign Up - New user</h1>
<%= render "form", user: @user %>
<%= link_to "Home", root_path %>

app/views/users/show.html.erb
<%= render "candidates/navbar"%>
<table class="table table-hover">
  <tr>
    <th>User ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email-ID</th>
    <th>Role</th>
  </tr>
  <tr>
    <td><a href="/users/<%= @user.id %>">
        <%= @user.id %>
    </a></td>
    <td><%= @user.first_name %></td>
    <td><%= @user.last_name %></td>
    <td><%= @user.email %></td>
    <td><%= @user.role.designation %></td>
  </tr>
</table>
<%# if is_hr || is_sd %>
<%# else %>
  <%= link_to "Edit", edit_user_path(@user) , class:"btn btn-outline-primary"%>
  <%= link_to "Destroy", user_path(@user), class:"btn btn-outline-primary",
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>

<%# end %>
<%= link_to "Back", users_path , class:"btn btn-outline-primary"%>