config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :users 
resources :candidates
# resources :job_posts
root "candidates#dashboard"
  # get 'sessions/new'
  get    'sign_in', to: 'sessions#new'
  post   'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'dashboard', to: 'candidates#dashboard'
  get 'approve/:id', to: 'users#approval', as: :approved
  get 'decline/:id', to: 'users#decline', as: :declined
  get 'probing', to: 'candidates#probing', as: :probing
  post 'probing', to: 'candidates#modify' 
  get 'docs_submission', to: 'candidate_clears#new'
  post 'docs_submission', to: 'candidate_clears#create'
  get 'docs_view', to: 'candidate_clears#index'
  get 'job_posts', to: 'job_posts#index'
  get 'job_posts/new', to: 'job_posts#new'
  post 'job_posts/new', to: 'job_posts#create'
  get '/job_post/:id', to: 'job_posts#show'
  get '/job_posts/:id/edit', to: 'job_posts#edit', as: :edit_jobpost
  put '/job_posts/:id', to: 'job_posts#update', as: :update_post
  delete '/job_posts/:id', to: 'job_posts#destroy'
  get 'post_approve/:id', to: 'job_posts#approval', as: :post_approved
  get 'post_decline/:id', to: 'job_posts#declined', as: :post_declined
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	has_one :CandidateClear
	has_one_attached :avatar
	belongs_to :candidate_reference
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, email:true
	validates :current_location, presence: true
	validates :experience, presence: true
	validates :current_designation, presence: true
	validates :availability_for_joining, presence: true
	validates :avatar, presence:true
	# before_save :status_update_check
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # before_action :require_login, except: [:new, :create, :dashboard, :edit, :modify, :update, :probing]
  before_action :status_update_check, only: [:create, :modify]
  before_action :change_update_date, only: [:update]
  # before_action :restrict, only: [:edit, :destroy]
  before_action :authenticate_user!, except: [:dashboard, :probing, :create, :new] 
	def index
    # if require_login
    #   redirect_to root_path
    # end
    search = params[:q]
    @candidates = if search
      Candidate.joins(:candidate_reference).where('first_name LIKE :search OR last_name LIKE :search OR current_designation LIKE :search OR candidate_references.name LIKE :search OR status LIKE :search' , search: "%#{search}%")
      # binding.pry
    else  
      Candidate.all
   end
	end

	def show 
    # binding.pry
		@candidate = Candidate.find(params[:id])
	end

	def new
    @candidate = Candidate.new
  end

  def create
    # binding.pry   
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to root_path, notice: "Your application is submitted"
    else  
      render :new
    end
  end

  def edit
    # binding.pry
    @candidate =  Candidate.find(params[:id])
  end

  def modify
    #binding.pry
   # @candidate =  Candidate.find_by(email: params[:email])
   @candidate =  Candidate.find_by(email: params[:candidate][:email])
   if @candidate.present? && @candidate.email == params[:candidate][:email] && @candidate.security_question == params[:candidate][:security_question] && @candidate.security_answer == params[:candidate][:security_answer]
    render :edit
    return
    else
      redirect_to probing_path, notice: 'incorrect data recieved'
      return
    end    
  end

  def status_update_check
    # binding.pry
    @candidate =  Candidate.find_by(email: params[:candidate][:email])
    if @candidate.present? && @candidate.status == "rejected"
      redirect_to root_path, notice: "your application has been rejected, please try again after #{@candidate.status_updated_at + 6.months}"
      return
    elsif @candidate.present? && @candidate.CandidateClear.present?
      redirect_to root_path, notice: "You have already submitted the documents"
      return
    elsif @candidate.present? && @candidate.status == "clear"
      redirect_to docs_submission_path, notice: "your application has been cleared, Please fill the form to process further"
    end
  end

  def update
    @candidate = Candidate.find(params[:id])
    if @candidate.update(candidate_params)
      if current_user
        redirect_to candidates_path, notice: "updated"
        return
      else
        redirect_to root_path, notice: "updated"
        return
      end
    else
      render :edit
    end
  end

  def change_update_date
    # binding.pry
    @candidate =  Candidate.find_by(email: params[:candidate][:email])
    if @candidate.status != params[:status]
      @candidate.update(status_updated_at: Time.now)
    end
  end

  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy
    # redirect_to candidates_path
    respond_to do |format|   
      format.html { redirect_to candidate_url, notice: "Candidate was Deleted" }   
      format.json { head :no_content }   
      format.js 
    end
  end
  
  def dashboard
  end

  def probing
  end

  def restrict
    redirect_to root_path unless current_user.role.designation == "Director" || current_user.role.designation == "Human Resource Executive"
    flash[:notice] = "You need to be admin/hr to edit. Please login as one"
  end
  
  private
  def candidate_params
    params.require(:candidate).permit(:first_name, :search, :last_name, :avatar, :email, :current_location, :experience, :current_designation, :availability_for_joining, :security_question, :security_answer, :candidate_reference_id, :status)
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<%= form_with model: @candidate do |form| %>
<div class="card">
  <div class="card-body">
    
    <div class="mb-3">
      <%= form.label :first_name, { class: "form-label"} %><br>
      <%= form.text_field :first_name, { class: "form-control" } %>
      <% @candidate.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :last_name, { class: "form-label"} %><br>
      <%= form.text_field :last_name, { class: "form-control" } %>
      <% @candidate.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :email, { class: "form-label"} %><br>
      <%= form.text_field :email, { class: "form-control" } %>
      <% @candidate.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :current_location, { class: "form-label"} %><br>
      <%= form.text_field :current_location, { class: "form-control" } %>
      <% @candidate.errors.full_messages_for(:current_location).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :experience, { class: "form-label"}%><br>
      <%= form.text_field :experience, { class: "form-control" } %>
      <% @candidate.errors.full_messages_for(:experience).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :current_designation, { class: "form-label"} %><br>
      <%= form.text_field :current_designation, { class: "form-control" } %>
      <% @candidate.errors.full_messages_for(:current_designation).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :availability_for_joining, { class: "form-label"} %><br>
      <%= form.date_field :availability_for_joining, attribute: 'date' %>
      <% @candidate.errors.full_messages_for(:availability_for_joining).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    &nbsp
    <div>
      <%= form.label :security_question , { class: "form-label"}%><br>
      <%= form.select :security_question,["What is your birthplace","Name of your first vehicle", "Who is your favorite relative"],{ class:"form-select form-select-lg mb-3" } %>
      <% @candidate.errors.full_messages_for(:security_answer).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div> 
    
    <div>
      <%= form.text_field :security_answer, { class: "form-control" } %>
      <% @candidate.errors.full_messages_for(:security_answer).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    &nbsp
    <div>
      <%= form.label :candidate_reference_id , { class: "form-label"}%>
      <%= form.select :candidate_reference_id, CandidateReference.all.pluck(:name, :id ),{ class:"form-select form-select-lg mb-3" } %>
      <% @candidate.errors.full_messages_for(:candidate_reference_id).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div> 
    &nbsp  
    <% if current_user%>
    <div>
      <%= form.label :status , { class: "form-label"}%>      
      <%= form.select :status,["applied","interview
    ", "hold", "clear", "rejected"],{ class:"form-select form-select-lg mb-3" } %>
    </div>
    <%end%>
      &nbsp
    <div>
    <%= form.file_field :avatar %>
    </div>
    &nbsp
    <div>
      <%= form.submit %>
    </div>
  </div>
</div>
<% end %>

<script>
$(document).ready(function() {
    $('#candidate_candidate_reference_id').select2({
      minimumInputLength: 3
    });
});
</script>

app/views/candidates/_index.html.erb
<table class="table table-hover">
  <tr>
    <th>Candidate ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Current Designation</th>
    <th>Reference</th>
    <th>Interview status</th>
  </tr>
  
  <% @candidates.each do |candidate| %>
  <tr id="candidateRow_<%=candidate.id%>">
    <td><a href="/candidates/<%= candidate.id %>">
        <%= candidate.id %>
    </a></td>
    <td><%= candidate&.first_name %></td>
    <td><%= candidate&.last_name %></td>
    <td><%= candidate&.current_designation %></td>
    <td><%= candidate.candidate_reference.name%></td>
    <td><%= candidate.status%></td>
    <td><%#= candidate.status_updated_at%></td>
    <%# if is_admin || is_hr %>
    <td><%= link_to "Destroy", candidate,
                  method: :delete,
                  data: { confirm: "Are you sure?" }, remote: true %>
    <% end %></td>
  </tr>
  <%# end %>
</table>

<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/candidates/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <%= link_to "ATS", root_path , { class: "navbar-brand" }%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "User management", users_path , { class: "nav-link active" }%>
        </li>
        <li class="nav-item" >
          <%= link_to "Candidate management", candidates_path , { class: "nav-link active" }%>
        </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item ms-auto">
          <%= link_to "Apply for Jobs", new_candidate_path , { class: "nav-link active" }%>         
        </li>
        <li class="nav-item ms-auto">
          <%= link_to "Update resume", probing_path , { class: "nav-link active" }%>
        </li>
        <li class="nav-item ms-auto">
          <%= link_to "Job Posts", job_posts_path , { class: "nav-link active" }%>
        </li>

        <% if current_user%>
        <li class="nav-item ">
          <!-- <a class="nav-link active" aria-current="page" href="logout_path"><%#= link_to "Log out", logout_path, method: :delete, class:"btn btn-outline-primary" %>  </a> -->
        </li>
        <li><%=link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <%else%>
        <li class="nav-item" >
          <%= link_to "User Sign In", user_session_path , { class: "nav-link active" }%>
        </li>
        <li class="nav-item ">
          <%= link_to "User Sign Up", new_user_path , { class: "nav-link active" }%>
        </li>

        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/candidates/dashboard.html.erb
<%= render "navbar"%>
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
   <%= msg %>
  </div>
<% end %>

app/views/candidates/destroy.js.erb
$("#candidateRow_<%= @candidate.id%>").fadeOut();

app/views/candidates/edit.html.erb
<%= render "navbar"%>
<h1>Edit your details</h1>
<%= render "form", candidate: @candidate %>
<%= link_to "Home", root_path %>

app/views/candidates/index.html.erb
<%= render "navbar"%>
<h1>Candidate details</h1>
<h5>Search</h5>
<%= form_tag(candidates_path, method: :get) do%>
<%= text_field_tag(:search, params[:search], id: "search_candidates")%>
<%#= submit_tag("Search")%>
<%end%>

<div id="candidates_table">
  <%= render "index"%>
</div>
<%= link_to "New candidate", new_candidate_path, class:"btn btn-outline-primary" %>
<%= link_to "Back", user_session_path, class:"btn btn-outline-primary" %>
<%= link_to "Home", root_path , class:"btn btn-outline-primary"%>
<%# if is_admin || is_hr %>
  <%= link_to "Cleared Candidates Docs", docs_view_path, class:"btn btn-outline-primary"%>
<%# end %>

<script type="text/javascript">
  $("#search_candidates").keyup(function(){
    text = $("#search_candidates").val();
    console.log("ajax called............" + text);
    $.ajax({
      type: 'GET',
      url: "/candidates.js",
      data: {"q": text}
    });
  });
</script>

app/views/candidates/index.js.erb
$("#candidates_table").html("<%= escape_javascript(render 'index') %>");

app/views/candidates/new.html.erb
<%= render "navbar"%>
<h1>New Candidate</h1>
<%= render "form", candidate: @candidate %>
<%= link_to "Home", root_path %>

app/views/candidates/probing.html.erb
<%= render "navbar"%>
<h3>Account Varification</h3>
&nbsp
<%= form_with model: @candidate, scope: "candidate" do |form| %>
  <div>
    <%= form.label :Enter_your_email %><br>
    <%= form.text_field :email %>
  </div>
    <div>
      <%= form.label :security_question , { class: "form-label"}%><br>
      <%= form.select :security_question,["What is your birthplace","Name of your first vehicle", "Who is your favorite relative"],{ class:"form-select form-select-lg mb-3" } %> 
    </div> 

    <div>
      <%= form.text_field :security_answer, { class: "form-control" } %>
    </div>

  <div>
    <%= form.submit %>
  </div>
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
     <%= msg %>
    </div>
  <% end%>
<%end%>

app/views/candidates/show.html.erb
<%= render "navbar"%>
<h3>Candidate Details</h3>
<table class="table table-hover">
  <tr>
    <th>Candidate ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Current Designation</th>
    <th>Experience</th>
    <th>Email</th>
    <th>Availability</th>
    <th>Current location</th>
    <th>Resume</th>
    <th>Preview</th>
  </tr>
  <tr>
    <td><a href="/candidates/<%= @candidate.id %>">
        <%= @candidate.id %>
    </a></td>
    <td><%= @candidate.first_name %></td>
    <td><%= @candidate.last_name %></td>
    <td><%= @candidate.current_designation %></td>
    <td><%= @candidate.experience %></td>
    <td><%= @candidate.email%></td>
    <td><%= @candidate.availability_for_joining %></td>
    <td><%= @candidate.current_location %></td>
    <td><%=link_to 'download', rails_blob_path(@candidate.avatar, disposition: "attachment")%></td>
    <td><%=link_to 'preview', rails_blob_path(@candidate.avatar, disposition: "preview"), target: '_blank'%></td>
  </tr>
</table>
<table  class="table table-hover">
  <tr>
    <th>Security Question</th>
    <th>Security Answer</th>
    <th>Reference</th>
    <th>Interview status</th>
  </tr>
<tr>
<td> <%= @candidate.security_question %></td>
<td><%= @candidate.security_answer %></td>
<td><%= @candidate.candidate_reference.name%></td>
<td><%= @candidate.status%></td>

</tr>
</table>
<%# if is_admin %>
    <%= link_to "Edit", edit_candidate_path(@candidate) , class:"btn btn-outline-primary"%>
    <%= link_to "Destroy", candidate_path(@candidate), class:"btn btn-outline-primary",           method: :delete,
                  data: { confirm: "Are you sure?" } %>
<%#elsif is_hr%>
    <%= link_to "Edit", edit_candidate_path(@candidate) , class:"btn btn-outline-primary"%>
<%# else %>
<%# end %>

<%= link_to "Back", candidates_path , class:"btn btn-outline-primary"%>