config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :users 
resources :candidates
# resources :job_posts
root "candidates#dashboard"
  # get 'sessions/new'
  get    'sign_in', to: 'sessions#new'
  post   'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'dashboard', to: 'candidates#dashboard'
  get 'approve/:id', to: 'users#approval', as: :approved
  get 'decline/:id', to: 'users#decline', as: :declined
  get 'probing', to: 'candidates#probing', as: :probing
  post 'probing', to: 'candidates#modify' 
  get 'docs_submission', to: 'candidate_clears#new'
  post 'docs_submission', to: 'candidate_clears#create'
  get 'docs_view', to: 'candidate_clears#index'
  get 'job_posts', to: 'job_posts#index'
  get 'job_posts/new', to: 'job_posts#new'
  post 'job_posts/new', to: 'job_posts#create'
  get '/job_post/:id', to: 'job_posts#show'
  get '/job_posts/:id/edit', to: 'job_posts#edit', as: :edit_jobpost
  put '/job_posts/:id', to: 'job_posts#update', as: :update_post
  delete '/job_posts/:id', to: 'job_posts#destroy'
  get 'post_approve/:id', to: 'job_posts#approval', as: :post_approved
  get 'post_decline/:id', to: 'job_posts#declined', as: :post_declined
end

app/models/job_post.rb
class JobPost < ApplicationRecord
	validates :job_title, presence: true
  validates :education_req, presence: true
  validates :experience_needed, presence: true
  validates :job_location, presence: true
  validates :job_type, presence: true
  validates :job_des, presence: true
	  enum status: {
    post_pending: 0, 
    post_approved: 1, 
    post_declined:2 
  }
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  # before_action :login_required, only: [:new, :create, :edit, :destroy]

  def index  
    # if current_user == nil || is_hr || is_sd
    # @jobposts =  JobPost.where(status: "post_approved")   
    # elsif is_admin     
      @jobposts =  JobPost.all   
    # end  
  end

	def new
    # if current_user == nil || current_user
      # elsif is_admin || is_hr
      @jobpost = JobPost.new
    # end
  end

	def show 
		# binding.pry
		@jobpost = JobPost.find(params[:id])
	end

  def create
    @jobpost = JobPost.new(job_post_params)
    if @jobpost.save
      # binding.pry
      redirect_to root_path, notice: "Your Job Posting request have been sent succesfully for approval"
    else
      render :new
    end
  end

  def edit
    # if is_sd 
      # flash[:error] = "You must be logged in as admin to access this action"
      # redirect_to root_path
    # else
      @jobpost = JobPost.find(params[:id])
    # end
  end

  def update
    @jobpost = JobPost.find(params[:id])
    if @jobpost.update(job_post_params)
      redirect_to job_posts_path, notice: "updated"
    else
      render :edit
    end
  end

  def destroy
    # if is_admin
      @jobpost = JobPost.find(params[:id])
      @jobpost.destroy
      redirect_to job_posts_path, notice: "record deleted"
      return
    # else
      # redirect_to job_posts_path, notice: "You need to be admin for deleting"
    # end
  end

  def approval
    @jobpost = JobPost.find(params[:id])
    @jobpost.post_approved!
    redirect_to job_posts_path
    flash[:notice] = "Post Approved"
  end

  def declined
    @jobpost = JobPost.find(params[:id])
    # binding.pry
    @jobpost.post_declined!
    redirect_to job_posts_path
    flash[:notice] = "Post Denied"
  end

  def login_required
    # binding.pry 
    if current_user == nil
      flash[:error] = "You must be logged in to access this section"
      redirect_to job_posts_path
    else
    end
  end


  private
  def job_post_params
  	# binding.pry
    params.require(:job_post).permit(:job_title, :user_id , :education_req, :email, :experience_needed, :job_location, :job_type, :job_des)
  end
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_form.html.erb
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<%= form_with model: @job_post, url: update_post_path ,method: :put, scope:"job_post" do |form| %>
<div class="card">
  <div class="card-body">
    
    <div class="mb-3">
      <%= form.label :job_title, { class: "form-label"} %><br>
      <%= form.text_field :job_title,  { class: "form-control", value: job_post.job_title } %>
      <% @jobpost.errors.full_messages_for(:job_title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :user_id, { class: "form-label"} %><br>
      <%= form.text_field :user_id, { class: "form-control" , value: job_post.user_id} %>
      <%# @jobpost.errors.full_messages_for(:job_title).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div>

    <div>
      <%= form.label :Educational_Required, { class: "form-label"} %><br>
      <%= form.text_field :education_req, { class: "form-control", value: job_post.education_req } %>
      <% @jobpost.errors.full_messages_for(:education_req).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :experience_needed, { class: "form-label"} %><br>
      <%= form.text_field :experience_needed, { class: "form-control", value: job_post.experience_needed } %>
      <% @jobpost.errors.full_messages_for(:experience_needed).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :job_location, { class: "form-label"} %><br>
      <%= form.text_field :job_location, { class: "form-control", value: job_post.job_location} %>
      <% @jobpost.errors.full_messages_for(:job_location).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :job_type, { class: "form-label"} %><br>
      <%= form.select :job_type,["on-site","hybrid", "wfo"],{ class:"form-select form-select-lg mb-3", value: job_post.job_type } %>
      <% @jobpost.errors.full_messages_for(:job_type).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    &nbsp
    <div>
      <%= form.label :job_description , { class: "form-label"}%><br>
      <%= form.text_area :job_des, { class: "form-control", value: job_post.job_des } %>
      <% @jobpost.errors.full_messages_for(:job_des).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div> 
    &nbsp
    <div>
      <%= form.submit 'update'%>
    </div>

  </div>
</div>
<%# end %>
<% end %>

app/views/job_posts/destroy.js.erb
$("#jobpostRow_<%= post.id%>").fadeOut();

app/views/job_posts/edit.html.erb
<%= render "candidates/navbar"%>
<h5>Edit</h5>
<%#binding.pry%>
<%= render "form", job_post: @jobpost%>

app/views/job_posts/index.html.erb
<%= render "candidates/navbar"%>
<table class="table table-hover">
  <tr>
  	<th>S.no</th>
    <th>Job Title</th>
    <th>Educational Required</th>
    <th>Experience needed</th>
    <th>job location</th>
    <th>job type</th>
  </tr>
  
  <% @jobposts.each do |post| %>

  <tr id="jobpostRow_<%=post.id%>">
    <td><a href="/job_post/<%= post.id %>">
        <%= post.id %>
    </a></td>
    <td><%= post&.job_title %></td>
    <td><%= post&.education_req %></td>
    <td><%= post&.experience_needed %> year</td>
    <td><%= post.job_location%></td>
    <td><%= post.job_type%></td>
    <%# if current_user == nil %>
    <%# elsif is_admin %>
    <td><%= link_to "Destroy", "/job_posts/#{post.id}",
                  method: :delete,
                  data: { confirm: "Are you sure?" }, remote: true %>
      <td><%= post.status%></td>
      <% if post.status == "post_declined"%>
      <%#binding.pry%>
        <td><%= link_to "Approve Post", post_approved_path(id: post.id)%></td>
      <% elsif post.status == "post_approved"%>
        <td><%= link_to "Decline Post", post_declined_path(id: post.id),
                  data: { confirm: "Are you sure?" }%></td>
      <%else%>
        <td><%= link_to "Approve Post", post_approved_path(id: post.id)%>
          &nbsp&nbsp
          <%= link_to "Decline Post", post_declined_path(id: post.id),
          data: { confirm: "Are you sure?" }%></td>
      <% end%>
    <%# end %></td>
  </tr>
  <% end %>
</table>
<%# if current_user == nil %>
<%# elsif is_admin || is_hr%>
  <%= link_to "New Job Post", job_posts_new_path, class:"btn btn-outline-primary" %>
<%# end %>
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/job_posts/new.html.erb
<%= render "candidates/navbar"%>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<%= form_with model: @job_post , scope:"job_post" do |form| %>
<div class="card">
  <div class="card-body">
    
    <div class="mb-3">
      <%= form.label :job_title, { class: "form-label"} %><br>
      <%= form.text_field :job_title,  { class: "form-control"} %>
      <%# @job_post.errors.full_messages_for(:job_title).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div>

    <div class="mb-3">
      <%= form.label :user_id, { class: "form-label"} %><br>
      <%= form.text_field :user_id, { class: "form-control"} %>
      <%# @job_post.errors.full_messages_for(:job_title).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div>

    <div>
      <%= form.label :Educational_Required, { class: "form-label"} %><br>
      <%= form.text_field :education_req, { class: "form-control"} %>
      <%# @job_post.errors.full_messages_for(:education_req).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div>

    <div>
      <%= form.label :experience_needed, { class: "form-label"} %><br>
      <%= form.text_field :experience_needed, { class: "form-control"} %>
      <%# @job_post.errors.full_messages_for(:experience_needed).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div>

    <div>
      <%= form.label :job_location, { class: "form-label"} %><br>
      <%= form.text_field :job_location, { class: "form-control"} %>
      <%# @job_post.errors.full_messages_for(:job_location).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div>

    <div>
      <%= form.label :job_type, { class: "form-label"} %><br>
      <%= form.select :job_type,["on-site","hybrid", "wfo"],{ class:"form-select form-select-lg mb-3" } %>
      <%# @job_post.errors.full_messages_for(:job_type).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div>
    &nbsp
    <div>
      <%= form.label :job_description , { class: "form-label"}%><br>
      <%= form.text_area :job_des, { class: "form-control" } %>
      <%# @job_post.errors.full_messages_for(:job_des).each do |message| %>
        <div><%#= message %></div>
      <%# end %>
    </div> 
    &nbsp
    <div>
      <%= form.submit %>
    </div>
  </div>
</div>
<%# end %>
<% end %>

app/views/job_posts/show.html.erb
<%= render "candidates/navbar"%>
<table class="table table-hover">
  <tr>
  	<th>S.no</th>
    <th>Job Title</th>
    <th>Educational Required</th>
    <th>Experience needed</th>
    <th>job location</th>
    <th>job type</th>
  </tr>
  
    <td><%= @jobpost.id %></td>
    <td><%= @jobpost&.job_title %></td>
    <td><%= @jobpost&.education_req %></td>
    <td><%= @jobpost&.experience_needed %> year</td>
    <td><%= @jobpost.job_location%></td>
    <td><%= @jobpost.job_type%></td>
    
    <% if current_user == nil %>
    <% elsif is_admin || is_hr %>
    <%= link_to "Edit", edit_jobpost_path(@jobpost) , class:"btn btn-outline-primary"%>
    <td><%= link_to "Destroy", "/job_posts/#{@jobpost.id}",
                  method: :delete,
                  data: { confirm: "Are you sure?" }, remote: true %>
    <% end %></td>
  </tr>
</table>
<h5>Job Description</h5>
<p><%= @jobpost.job_des%></p>